meta_product_name: "Lost & Found"
meta_title: "Lost & Found – for the greater good!"
meta_description: "Contribute to the local community, help people get their belongings back – and find your lost beloved items!"
meta_image: "og.png" # should exist in `app/assets/images/`
